#!/usr/bin/perl -w

# Convert an input file containing a Graph::Easy description to
# standalone SVG file

# Example usage:
#  examples/as_svg t/in/2nodes.txt >test.svg
#  echo "[ A ] -> [ B ]" | examples/as_svg

BEGIN { $|++; }

use strict;
use lib 'lib';
use Graph::Easy::Parser;

my $file = shift;

my $parser = Graph::Easy::Parser->new( debug => 0 );

$file = \*STDIN unless defined $file;
my $graph = $parser->from_file( $file );

die ($parser->error()) unless defined $graph;
$graph->layout();
warn ($graph->error()) if $graph->error();

print $graph->as_svg( { standalone => 1 } );

